In [22]:
# importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

# Machine learning packages
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import scale 
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LassoCV,LinearRegression

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix


In [23]:
df = pd.read_csv('data.csv')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399284 entries, 0 to 399283
Data columns (total 33 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   Unnamed: 0            399284 non-null  int64  
 1   App Name              399283 non-null  object 
 2   App Id                399284 non-null  object 
 3   Category              399284 non-null  object 
 4   Rating                399284 non-null  float64
 5   Rating Count          399284 non-null  float64
 6   Installs              399284 non-null  float64
 7   Minimum Installs      399284 non-null  float64
 8   Maximum Installs      399284 non-null  int64  
 9   Free                  399284 non-null  bool   
 10  Price                 399284 non-null  float64
 11  Currency              399284 non-null  object 
 12  Size                  399284 non-null  float64
 13  Minimum Android       398998 non-null  object 
 14  Released              399284 non-null  object 
 15  

In [25]:
df = df.drop(['Unnamed: 0'],axis=1)

In [26]:
df.sample(5)

App Name  ... dayssincechange
99130                           Note Anytime  ...             817
252351                    Malappuram Tourism  ...             503
344234        Guide to the Big Island Hawaii  ...              89
219153  Notepad Lite for Notes and ToDo List  ...               0
258879           Juego del Mapa de Venezuela  ...               0

[5 rows x 32 columns]

In [27]:
df_app_notfree = df[df['Free'] == False]
df_app_free = df[df['Free'] == True]

print('There are {} Not-Free Apps in this dataset'.format(df_app_notfree.shape[0]))
print('There are {} Free Apps in this dataset'.format(df_app_free.shape[0]))

There are 18281 Not-Free Apps in this dataset
There are 381003 Free Apps in this dataset


In [28]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score, cross_validate

In [29]:
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399284 entries, 0 to 399283
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   App Name              399283 non-null  object 
 1   App Id                399284 non-null  object 
 2   Category              399284 non-null  object 
 3   Rating                399284 non-null  float64
 4   Rating Count          399284 non-null  float64
 5   Installs              399284 non-null  float64
 6   Minimum Installs      399284 non-null  float64
 7   Maximum Installs      399284 non-null  int64  
 8   Free                  399284 non-null  bool   
 9   Price                 399284 non-null  float64
 10  Currency              399284 non-null  object 
 11  Size                  399284 non-null  float64
 12  Minimum Android       398998 non-null  object 
 13  Released              399284 non-null  object 
 14  Last Updated          399284 non-null  object 
 15  

In [31]:
df = df.drop(['Free','Currency','Released','Minimum Installs','Maximum Installs','Minimum Android','Last Updated','Content Rating','Ad Supported','In App Purchases','Editors Choice','App Name','App Id','Category'], axis = 1)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399284 entries, 0 to 399283
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   Rating                399284 non-null  float64
 1   Rating Count          399284 non-null  float64
 2   Installs              399284 non-null  float64
 3   Price                 399284 non-null  float64
 4   Size                  399284 non-null  float64
 5   c_lifestyle           399284 non-null  float64
 6   c_education           399284 non-null  float64
 7   c_health              399284 non-null  float64
 8   c_travel              399284 non-null  float64
 9   c_communication       399284 non-null  float64
 10  c_news                399284 non-null  float64
 11  c_tools               399284 non-null  float64
 12  c_weather             399284 non-null  float64
 13  c_business            399284 non-null  float64
 14  c_entertainment       399284 non-null  float64
 15  

In [33]:
df_train = df.drop(['Rating'],axis=1)
target = df['Rating']
def categorize_rating(x):
    if x <= 1.6:
        return 0
    else:
        return 1

target = target.apply(categorize_rating)

In [34]:
X_train, X_test, y_train, y_test = train_test_split(df_train, target, test_size=0.2, random_state=1989, stratify=target)

print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)

X_train shape: (319427, 17)
X_test shape: (79857, 17)


In [36]:
from sklearn import model_selection
# random forest model creation
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
# predictions
rfc_predict = rfc.predict(X_test)
rfc_cv_score = cross_val_score(rfc, df_train, target, cv=10, scoring='roc_auc')
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, rfc_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, rfc_predict))
print('\n')
print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ", rfc_cv_score.mean())

=== Confusion Matrix ===
[[ 5344 18140]
 [ 4988 51385]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.52      0.23      0.32     23484
           1       0.74      0.91      0.82     56373

    accuracy                           0.71     79857
   macro avg       0.63      0.57      0.57     79857
weighted avg       0.67      0.71      0.67     79857



=== All AUC Scores ===
[0.67311158 0.66109386 0.65795763 0.64740087 0.6251008  0.61518712
 0.61175008 0.6408115  0.64600769 0.65061212]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.6429033261199687


In [37]:
rfc = XGBClassifier()
rfc.fit(X_train,y_train)
# predictions
rfc_predict = rfc.predict(X_test)
rfc_cv_score = cross_val_score(rfc, df_train, target, cv=10, scoring='roc_auc')
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, rfc_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, rfc_predict))
print('\n')
print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - XGBoost Forest: ", rfc_cv_score.mean())

=== Confusion Matrix ===
[[ 1210 22274]
 [  824 55549]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.59      0.05      0.09     23484
           1       0.71      0.99      0.83     56373

    accuracy                           0.71     79857
   macro avg       0.65      0.52      0.46     79857
weighted avg       0.68      0.71      0.61     79857



=== All AUC Scores ===
[0.68664371 0.66589455 0.68221787 0.68174334 0.65589592 0.64055628
 0.6443467  0.66600891 0.66189859 0.66198867]


=== Mean AUC Score ===
Mean AUC Score - XGBoost Forest:  0.6647194548444881


In [38]:
rfc = LGBMClassifier()
rfc.fit(X_train,y_train)
# predictions
rfc_predict = rfc.predict(X_test)
rfc_cv_score = cross_val_score(rfc, df_train, target, cv=10, scoring='roc_auc')
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, rfc_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, rfc_predict))
print('\n')
print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - LGBM Forest: ", rfc_cv_score.mean())

=== Confusion Matrix ===
[[ 2735 20749]
 [ 2015 54358]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.58      0.12      0.19     23484
           1       0.72      0.96      0.83     56373

    accuracy                           0.71     79857
   macro avg       0.65      0.54      0.51     79857
weighted avg       0.68      0.71      0.64     79857



=== All AUC Scores ===
[0.69988105 0.68952588 0.6894375  0.68911163 0.6614828  0.65230413
 0.65187169 0.67462186 0.67017879 0.67243784]


=== Mean AUC Score ===
Mean AUC Score - LGBM Forest:  0.675085315559503


In [39]:
models = [RandomForestClassifier(), LGBMClassifier(), XGBClassifier()]

kfold = KFold(n_splits=5, random_state=1989)

clf_comparison = pd.DataFrame(columns=['Classfier_name', 'train_score', 'test_score'])

for i, model in enumerate(models):
    clf = model
    cv_result = cross_validate(model, X_train, y_train, cv=kfold, scoring='accuracy',return_train_score=True)
    clf_comparison.loc[i, 'Classfier_name'] = model.__class__.__name__
    clf_comparison.loc[i, 'train_score'] = cv_result['train_score'].mean()
    clf_comparison.loc[i, 'test_score'] = cv_result['test_score'].mean()

clf_comparison

Classfier_name train_score test_score
0  RandomForestClassifier    0.999901   0.710635
1          LGBMClassifier    0.720151   0.715985
2           XGBClassifier    0.711429   0.711148

In [ ]:
feat_importances = pd.Series(model.feature_importances_, index=df_train.columns)
feat_importances.nlargest(15).sort_values().plot(kind='barh', color='darkgrey', figsize=(10,5))
plt.xlabel('Relative Feature Importance with XGBoost');